### ISSUE TITLE
Reemplazer CRA (Create-React-App) por Vite

### ISSUE THREAD

**Issue by mikedev64** [yuc96/classonlineproject#1]
# Solicitud Para Reemplazar CRA por Vite
Viendo el proyecto desde el inicio, recomiendo cambiar la instalacion de [Create-React-App](https://github.com/facebook/create-react-app) por la instalacion de [Vite](https://vitejs.dev/), esto por temas de seguridad, siendo que ***Create React App*** esta deprecada, basándome también en la propia [documentación de ReactJs](https://react.dev/learn/start-a-new-react-project).

![Documentación especifica de ReactJs](https://github.com/yuc96/classonlineproject/assets/84690368/bc9ffeae-3e40-4ac4-a91e-b3212e5e1f6c)
> [!NOTE]
> con Npm
> ```sh
> npm create vite@latest
> ```
> con Pnpm
> ```sh
> $ pnpm create vite
> ```
> con Bun
> ```sh
> $ bunx create-vite
> ```

**Comment by yuc96** [comment]
Si bien es correcto todo lo que mencionas en temas de seguridad y compatibilidad con módulos nativos,pero tengo dudas sobre Vite en temas de compatibilidad con plugins, que se puedan incorporar en el camino, pero toma en consideración estas limitaciones

Compatibilidad con bibliotecas y plugins: Aunque Vite tiene un ecosistema de plugins en crecimiento, puede que no sea tan extenso como el de otras herramientas más establecidas como Webpack1. Esto podría limitar las opciones de personalización y extensión de tu proyecto.
 Configuración y personalización: Vite viene con una configuración predeterminada que puede no ser adecuada para todos los proyectos1. Si tu proyecto requiere una configuración muy específica o compleja, puede que encuentres algunas limitaciones. Soporte y comunidad: Aunque Vite está ganando popularidad, todavía es una herramienta relativamente nueva en comparación con otras como Webpack o Rollup1. Esto significa que puede haber menos recursos de aprendizaje disponibles, menos soluciones a problemas comunes y una comunidad de soporte más pequeña.
 Proyectos a gran escala: Para proyectos a gran escala que requieren configuraciones complejas, otras herramientas como Create React App podrían seguir siendo una opción viable
 
 En base a esto me gustaria tu opinión

**Comment by yuc96** [comment]
Pero podríamos usar next.js, veo que tiene muchas ventajas sobre React Create App

**Comment by mikedev64** [comment]
Si, entiendo los puntos que mencionas sobre la compatibilidad y estoy de acuerdo contigo, si lo vemos por ese lado no veo ningún problema, en el caso de usar NextJs, tendríamos que tener en cuenta que como poseemos una API de microservicios para la web, no lo vería tan necesario, por lo que si, podemos quedarnos con CRA, solo daba una sugerencia por los temas mencionados anteriormente.
